### ISSUE TITLE
Resizing animated GIFs to 400px only

### ISSUE THREAD

**Issue by FanrayMedia** [FanrayMedia/Fanray#282]
## Overview

Using Magick.NET to resize a gif, depending on file size, could take a long time. As part of the effort to use ImageSharp #249 instead for image resizing. I will implement new logic on resizing gif.  Related issue also include #264.

This issue has been addressed when I switched from Magick.NET to ImageSharp see #249

**Comment by flyznex** [comment]
I found this topic [Slow gif generation](https://www.imagemagick.org/discourse-server/viewtopic.php?f=27&t=27919#p125329). It's maybe that you need to fix this bug
