### ISSUE TITLE
Use Humanizer instead of ByteSize for file size calculation

### ISSUE THREAD

**Issue by skalavala** [FanrayMedia/Fanray#347]
You've done such a nice job of writing and sharing this with the community. Love the way you structured the code, and appropriate use of design patterns.

I'm sure you are aware, If not, I suggest [Humanizer](https://github.com/Humanizr/Humanizer#bytesize) library. There are so many things you could leverage out of the box and keeps things simple. You could pretty much replace ByteSize helper class (no need to roll your own), and also use date formats and other conversions using Fluent API.

Just thought I'd share, otherwise your repo is fantastic!

**Comment by FanrayMedia** [comment]
@skalavala Thank you so much for your kind words, so glad to know you liked it. I saw your awesome automation project, it looks really interesting and with great potential.

Currently I'm using Humanizer to display user friendly datetime of a post, I wasn't aware it could also do the ByteSize thing, thank you for pointing that out for me. It definitely will save me a class to keep around, I'll look into this.

Thank you for sharing and if you see anything that could be improved please feel free to drop me a note!
