### ISSUE TITLE
Unit test refactoring

### ISSUE THREAD

**Issue by Makulak** [FanrayMedia/Fanray#354]
I noticed that several unit tests can be improved, for example:

1. IsValidEmail_Test - it should be two tests, one checking invalid email, second one valid one.
2. Create_category_throws_FanException_if_title_already_exists - it is not necessary to call function in try-catch.

I will create a pull request with fixes suggestions.

**Comment by FanrayMedia** [comment]
I have manually incorporated your suggestions in, I'm skipping the PR merging. Thank you!
